package com.learnova.audit.enums;

public enum AuditAction {
    PASSWORD_CHANGED,
    GOOGLE_ACCOUNT_LINKED,
    ONBOARDING_COMPLETED,
    ROLE_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    EXAM_VERSION_PUBLISHED,
    EXAM_ARCHIVED,
    SESSION_CREATED,
    SESSION_CANCELLED,
    SESSION_END_TIME_EXTENDED,
    RESULT_MANUALLY_RELEASED
}
